# Generated by Django 4.2.11 on 2025-04-20 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_product_category_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='on_deal',
            field=models.BooleanField(default=False),
        ),
    ]
